// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Source: ALL_CALCULATORS_META, CATEGORIES, TOOL_CONFIGS, ALL_CHECKLISTS
// Generator: scripts/generate-route-manifest.ts
//
// Назначение — валидация адресов в middleware (Edge runtime) до начала стриминга,
// чтобы несуществующие страницы отдавали настоящий 404, а не 200 с пустым телом.
// Здесь только строки: middleware не должен тянуть Node-зависимости приложения.
//
// Синхронность с источниками проверяет тест route-manifest-sync.test.ts.
// Обновить: npm run sync:routes

/** Категории калькуляторов: /kalkulyatory/<category>/ */
export const ROUTE_CATEGORY_SLUGS: readonly string[] = [
  "fasad",
  "fundament",
  "inzhenernye",
  "krovlya",
  "otdelka",
  "poly",
  "potolki",
  "steny"
];

/** Slug калькуляторов: /kalkulyatory/<category>/<slug>/ */
export const ROUTE_CALCULATOR_SLUGS: readonly string[] = [
  "armatura",
  "beton",
  "dekorativnaya-shtukaturka",
  "dekorativnyj-kamen",
  "drenazh-uchastka",
  "elektrika",
  "fasadnye-paneli",
  "gazobeton",
  "gazon",
  "gidroizolyaciya-vlagozaschita",
  "gipsokarton",
  "gruntovka",
  "kalkulyator-lestnicy",
  "kalkulyator-terrasnoy-doski",
  "karkasnyj-dom",
  "kassetnyi-potolok",
  "kirpich",
  "kladka-kirpicha",
  "klej-dlya-plitki",
  "kraska",
  "krepezh",
  "krovlya",
  "laminat",
  "lentochnyy-fundament",
  "linoleum",
  "myagkaya-krovlya",
  "nalivnoy-pol",
  "natyazhnoj-potolok",
  "oblitsovochnyj-kirpich",
  "oboi",
  "otdelka-balkona",
  "otdelka-mansardy",
  "otkosy-okon-i-dverej",
  "otmostka",
  "otoplenie-radiatory",
  "paneli-dlya-sten",
  "parket",
  "penobloki",
  "peregorodki-iz-blokov",
  "plitka",
  "plitnyj-fundament",
  "podval-fundamenta",
  "podvesnoy-potolok-gkl",
  "reechnyj-potolok",
  "sayding",
  "septik",
  "septik-iz-kolets",
  "shpaklevka",
  "shtukaturka",
  "styazhka",
  "teplitsa-iz-polikarbonata",
  "teplyy-pol",
  "trotuarnaya-plitka",
  "ustanovka-dverej",
  "ustanovka-okon",
  "uteplenie",
  "uteplenie-fasada-minvatoj",
  "uteplenie-potolka",
  "vannaya-komnata",
  "ventilyaciya",
  "vodostok",
  "vodyanoy-teplyy-pol",
  "zabor",
  "zatirka",
  "zvukoizolyaciya"
];

/** Каноническая категория калькулятора — для 301 при обращении по чужой категории. */
export const ROUTE_CALCULATOR_CATEGORY: Readonly<Record<string, string>> = {
  "beton": "fundament",
  "lentochnyy-fundament": "fundament",
  "plitnyj-fundament": "fundament",
  "otmostka": "fundament",
  "podval-fundamenta": "fundament",
  "armatura": "fundament",
  "kirpich": "steny",
  "gipsokarton": "steny",
  "gazobeton": "steny",
  "penobloki": "steny",
  "kladka-kirpicha": "steny",
  "karkasnyj-dom": "steny",
  "shtukaturka": "steny",
  "paneli-dlya-sten": "steny",
  "peregorodki-iz-blokov": "steny",
  "plitka": "poly",
  "zatirka": "poly",
  "klej-dlya-plitki": "poly",
  "laminat": "poly",
  "parket": "poly",
  "linoleum": "poly",
  "styazhka": "poly",
  "nalivnoy-pol": "poly",
  "teplyy-pol": "inzhenernye",
  "natyazhnoj-potolok": "potolki",
  "reechnyj-potolok": "potolki",
  "kassetnyi-potolok": "potolki",
  "uteplenie-potolka": "potolki",
  "podvesnoy-potolok-gkl": "potolki",
  "krovlya": "krovlya",
  "vodostok": "krovlya",
  "myagkaya-krovlya": "krovlya",
  "uteplenie": "fasad",
  "uteplenie-fasada-minvatoj": "fasad",
  "sayding": "fasad",
  "fasadnye-paneli": "fasad",
  "oblitsovochnyj-kirpich": "fasad",
  "dekorativnaya-shtukaturka": "fasad",
  "dekorativnyj-kamen": "otdelka",
  "zabor": "fasad",
  "kalkulyator-terrasnoy-doski": "fasad",
  "trotuarnaya-plitka": "fasad",
  "teplitsa-iz-polikarbonata": "fasad",
  "gazon": "fasad",
  "kalkulyator-lestnicy": "otdelka",
  "elektrika": "inzhenernye",
  "otoplenie-radiatory": "inzhenernye",
  "ventilyaciya": "inzhenernye",
  "vodyanoy-teplyy-pol": "inzhenernye",
  "septik": "inzhenernye",
  "septik-iz-kolets": "inzhenernye",
  "drenazh-uchastka": "inzhenernye",
  "oboi": "otdelka",
  "kraska": "otdelka",
  "gruntovka": "otdelka",
  "shpaklevka": "otdelka",
  "gidroizolyaciya-vlagozaschita": "otdelka",
  "ustanovka-dverej": "otdelka",
  "ustanovka-okon": "otdelka",
  "otkosy-okon-i-dverej": "otdelka",
  "zvukoizolyaciya": "otdelka",
  "otdelka-balkona": "otdelka",
  "otdelka-mansardy": "otdelka",
  "vannaya-komnata": "otdelka",
  "krepezh": "otdelka"
};

/** Slug инструментов: /instrumenty/<slug>/ */
export const ROUTE_TOOL_SLUGS: readonly string[] = [
  "chek-listy",
  "kalendar-remonta",
  "konverter",
  "lineynyy-raskroy",
  "moy-remont",
  "normy-raskhoda",
  "ploshchad-komnaty",
  "raskladka-kirpicha",
  "raskladka-laminata",
  "raskladka-listov",
  "raskladka-oboev",
  "raskladka-plitki",
  "raskladka-reek",
  "raskladka-terrasnoy-doski",
  "raskladka-trotuarnoy-plitki",
  "rasstanovka-svetilnikov",
  "skolko-ostalos",
  "sravnenie-materialov",
  "stoimost-remonta",
  "tajmer-skhvatyvaniya"
];

/** Slug чек-листов: /instrumenty/chek-listy/<slug>/ */
export const ROUTE_CHECKLIST_SLUGS: readonly string[] = [
  "montazh-gipsokartona",
  "montazh-krovli",
  "pokleivaniye-oboev",
  "pokraska-sten",
  "razvodka-elektriki",
  "remont-kvartiry",
  "styazhka-pola",
  "ukladka-plitki",
  "ustanovka-santehniki",
  "ustroystvo-fundamenta",
  "uteplenie-fasada"
];
