"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useMemo, useRef, useState } from "react";
import SaveToProjectButton from "@/components/calculator/SaveToProjectButton";
import CompactToolWorkspaceNav from "@/components/tools/CompactToolWorkspaceNav";
import { ToolMetric, ToolNotes, ToolNumberInput, ToolPresetButton } from "@/components/tools/VisualToolPrimitives";
import { useToolAnalytics } from "@/components/tools/useToolAnalytics";
import { trackToolRelatedClick } from "@/lib/analytics";
import { calculatePaverLayout, type PaverPattern } from "@/lib/tools/paver-layout";
import {
  buildPavingCalculatorHrefFromLayout,
  readPaverLayoutHints,
} from "@/lib/tools/paver-layout-to-calc";

const PAVER_PRESETS = [{ label: "Кирпич 200 × 100", length: 200, width: 100 }, { label: "Брусчатка 100 × 100", length: 100, width: 100 }, { label: "Плита 300 × 300", length: 300, width: 300 }, { label: "Плита 600 × 300", length: 600, width: 300 }] as const;
const COLORS = ["#a84c3c", "#b85b48", "#914437", "#c46a55", "#9f5142"];
type PaverWorkspaceStage = "parameters" | "layout" | "result";
const PAVER_WORKSPACE_STAGES = [
  { value: "parameters", shortLabel: "Параметры", label: "Площадка и плитка" },
  { value: "layout", shortLabel: "Схема", label: "Рисунок и подрезки" },
  { value: "result", shortLabel: "Результат", label: "Итог к покупке" },
] satisfies Array<{ value: PaverWorkspaceStage; shortLabel: string; label: string }>;

function PavingSvg({ result }: { result: ReturnType<typeof calculatePaverLayout> }) {
  const width = result.input.surfaceWidthMm; const height = result.input.surfaceLengthMm; const unit = Math.min(width, height); const pad = unit * .14; const joint = result.input.jointMm;
  let y = 0;
  return <svg viewBox={`${-pad} ${-pad} ${width + pad * 2} ${height + pad * 2}`} className="h-auto w-full" role="img" aria-label={`Площадка с раскладкой из ${result.purchasePavers} элементов к покупке`}>
    <defs><pattern id="paver-grass" width={unit / 15} height={unit / 15} patternUnits="userSpaceOnUse"><rect width="100%" height="100%" fill="#cfe3c2" /><path d={`M 0 ${unit / 25} Q ${unit / 40} 0 ${unit / 22} ${unit / 28}`} stroke="#6f9a65" strokeWidth={unit / 300} fill="none" opacity=".6" /></pattern><filter id="paver-shadow"><feDropShadow dx="0" dy={unit / 70} stdDeviation={unit / 75} floodColor="#0f172a" floodOpacity=".22" /></filter></defs>
    <rect x={-pad} y={-pad} width={width + pad * 2} height={height + pad * 2} rx={unit / 26} fill="url(#paver-grass)" />
    <g filter="url(#paver-shadow)"><rect x={-unit * .025} y={-unit * .025} width={width + unit * .05} height={height + unit * .05} fill="#8b8177" stroke="#57534e" strokeWidth={unit / 250} />
      {result.grid.map((row, rowIndex) => { let x = 0; const rowHeight = row[0]?.heightMm ?? 0; const cells = row.map((cell, colIndex) => { const currentX = x; x += cell.widthMm + (colIndex < row.length - 1 ? joint : 0); return <g key={`${rowIndex}-${colIndex}`}><rect x={currentX} y={y} width={cell.widthMm} height={cell.heightMm} rx={Math.min(5, unit / 130)} fill={COLORS[(rowIndex * 3 + colIndex) % COLORS.length]} stroke="#f1d2c9" strokeWidth={Math.max(1, joint * .6)} />{cell.type !== "whole" && cell.widthMm > unit / 30 && cell.heightMm > unit / 30 && <path d={`M ${currentX} ${y} L ${currentX + cell.widthMm} ${y + cell.heightMm}`} stroke="#fff7ed" strokeOpacity=".55" strokeWidth={unit / 170} />}</g>; }); y += rowHeight + (rowIndex < result.grid.length - 1 ? joint : 0); return <g key={rowIndex}>{cells}</g>; })}
    </g>
    <text x={width / 2} y={-pad * .42} textAnchor="middle" fill="#334155" fontSize={Math.max(45, unit / 29)} fontWeight="650">{width.toLocaleString("ru-RU")} × {height.toLocaleString("ru-RU")} мм</text>
  </svg>;
}

export default function PaverLayoutPlanner() {
  const searchParams = useSearchParams();
  const transferredHints = useMemo(() => readPaverLayoutHints(searchParams), [searchParams]);
  const [activeStage, setActiveStage] = useState<PaverWorkspaceStage>("layout");
  const [surfaceWidth, setSurfaceWidth] = useState(3000); const [surfaceLength, setSurfaceLength] = useState(5000); const [paverWidth, setPaverWidth] = useState(100); const [paverLength, setPaverLength] = useState(200); const [joint, setJoint] = useState(3); const [pattern, setPattern] = useState<PaverPattern>("offset-half"); const [reserve, setReserve] = useState(7);
  const workspaceTopRef = useRef<HTMLDivElement>(null); const parametersRef = useRef<HTMLDivElement>(null); const layoutRef = useRef<HTMLDivElement>(null); const resultRef = useRef<HTMLDivElement>(null);
  const { markStarted, selectMode } = useToolAnalytics("raskladka-trotuarnoy-plitki", resultRef);
  const result = useMemo(() => calculatePaverLayout({ surfaceWidthMm: surfaceWidth, surfaceLengthMm: surfaceLength, paverWidthMm: paverWidth, paverLengthMm: paverLength, jointMm: joint, pattern, reservePercent: reserve }), [joint, pattern, paverLength, paverWidth, reserve, surfaceLength, surfaceWidth]);
  const calculatorHref = useMemo(() => buildPavingCalculatorHrefFromLayout(result), [result]);
  const materials = useMemo(() => [{ name: `Тротуарная плитка ${result.input.paverLengthMm} × ${result.input.paverWidthMm} мм`, quantity: result.purchasePavers, unit: "шт.", category: "Благоустройство" }], [result]);
  const start = () => markStarted("material_size");
  const changeStage = useCallback((stage: PaverWorkspaceStage) => {
    setActiveStage(stage);
    window.requestAnimationFrame(() => workspaceTopRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }));
  }, []);
  return <div ref={workspaceTopRef} className="space-y-4 scroll-mt-24 xl:grid xl:grid-cols-[minmax(280px,0.85fr)_minmax(0,1.65fr)_minmax(280px,0.85fr)] xl:items-start xl:gap-4 xl:space-y-0">
    {transferredHints && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800 dark:border-rose-900/50 dark:bg-rose-950/20 dark:text-rose-300 xl:col-span-3" data-testid="paver-layout-transfer-banner">В калькуляторе было {transferredHints.areaM2.toLocaleString("ru-RU")} м² и {transferredHints.perimeterM.toLocaleString("ru-RU")} м периметра. Стороны не восстановлены автоматически: площадь и периметр могут описывать непрямоугольную площадку. Введите размеры внутри бордюров по плану или замерам.</div>}
    <div className="xl:col-span-3">
    <CompactToolWorkspaceNav activeStage={activeStage} ariaLabel="Этапы раскладки тротуарной плитки" stages={PAVER_WORKSPACE_STAGES} onChange={changeStage} metrics={[
      { label: "Площадь", value: `${result.areaM2} м²` },
      { label: "Ряды", value: `${result.rows} шт.` },
      { label: "Подрезки", value: `${result.cutPieces} шт.` },
      { label: "Купить", value: `${result.purchasePavers} шт.`, accent: true },
    ]} />
    </div>

    <div ref={parametersRef} className={`card scroll-mt-24 space-y-4 border-stone-200 bg-[#fffdf9] p-4 dark:border-slate-700 dark:bg-slate-900 sm:p-6 xl:col-start-1 xl:row-start-2 xl:block xl:sticky xl:top-20 ${activeStage === "parameters" ? "block" : "hidden"}`}>
      <div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-rose-700 dark:text-rose-300">Шаг 1</p><h2 className="mt-1 text-xl font-bold text-stone-950 dark:text-white">Параметры раскладки</h2><p className="mt-1 text-sm text-stone-500 dark:text-slate-400">Размер внутри бордюров, формат плитки и рисунок.</p></div>
      <details open className="group rounded-2xl border border-stone-200 bg-white dark:border-slate-700 dark:bg-slate-950"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 [&::-webkit-details-marker]:hidden"><span><span className="block text-sm font-semibold text-stone-950 dark:text-white">Размер площадки</span><span className="mt-0.5 block text-xs text-stone-500 dark:text-slate-400">{surfaceWidth.toLocaleString("ru-RU")} × {surfaceLength.toLocaleString("ru-RU")} мм внутри бордюров</span></span><span aria-hidden="true" className="text-lg text-stone-400 transition-transform group-open:rotate-45">＋</span></summary><div className="grid gap-4 border-t border-stone-100 px-4 pb-4 pt-3 sm:grid-cols-2 dark:border-slate-800"><ToolNumberInput label="Ширина площадки" value={surfaceWidth} unit="мм" min={300} max={20000} step={10} onChange={(v) => { start(); setSurfaceWidth(v); }} /><ToolNumberInput label="Длина площадки" value={surfaceLength} unit="мм" min={300} max={20000} step={10} onChange={(v) => { start(); setSurfaceLength(v); }} /></div></details>
      <details className="group rounded-2xl border border-stone-200 bg-white dark:border-slate-700 dark:bg-slate-950"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 [&::-webkit-details-marker]:hidden"><span><span className="block text-sm font-semibold text-stone-950 dark:text-white">Формат плитки</span><span className="mt-0.5 block text-xs text-stone-500 dark:text-slate-400">{paverLength} × {paverWidth} мм · шов {joint} мм</span></span><span aria-hidden="true" className="text-lg text-stone-400 transition-transform group-open:rotate-45">＋</span></summary><div className="space-y-3 border-t border-stone-100 px-4 pb-4 pt-3 dark:border-slate-800"><div className="grid gap-4 sm:grid-cols-3"><ToolNumberInput label="Ширина элемента" value={paverWidth} unit="мм" min={40} max={1000} onChange={(v) => { start(); setPaverWidth(v); }} /><ToolNumberInput label="Длина элемента" value={paverLength} unit="мм" min={40} max={1000} onChange={(v) => { start(); setPaverLength(v); }} /><ToolNumberInput label="Шов" value={joint} unit="мм" min={0} max={10} step={0.5} onChange={(v) => { start(); setJoint(v); }} /></div><div className="flex flex-wrap gap-2">{PAVER_PRESETS.map((preset) => <ToolPresetButton key={preset.label} active={paverLength === preset.length && paverWidth === preset.width} onClick={() => { markStarted("preset"); setPaverLength(preset.length); setPaverWidth(preset.width); }}>{preset.label}</ToolPresetButton>)}</div></div></details>
      <details className="group rounded-2xl border border-stone-200 bg-white dark:border-slate-700 dark:bg-slate-950"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 [&::-webkit-details-marker]:hidden"><span><span className="block text-sm font-semibold text-stone-950 dark:text-white">Рисунок и запас</span><span className="mt-0.5 block text-xs text-stone-500 dark:text-slate-400">{pattern === "straight" ? "Прямые швы" : pattern === "offset-half" ? "Смещение ½" : "Смещение ⅓"} · запас {reserve}%</span></span><span aria-hidden="true" className="text-lg text-stone-400 transition-transform group-open:rotate-45">＋</span></summary><div className="grid gap-4 border-t border-stone-100 px-4 pb-4 pt-3 sm:grid-cols-2 dark:border-slate-800"><label><span className="mb-1.5 block text-xs font-medium text-slate-600 dark:text-slate-300">Рисунок</span><select value={pattern} onChange={(e) => { selectMode(e.target.value); setPattern(e.target.value as PaverPattern); }} className="input-field w-full"><option value="straight">Прямые швы</option><option value="offset-half">Смещение ½</option><option value="offset-third">Смещение ⅓</option></select></label><ToolNumberInput label="Закрытый запас" value={reserve} unit="%" min={0} max={30} onChange={(v) => { start(); setReserve(v); }} /></div></details>
      <button type="button" onClick={() => changeStage("layout")} className="btn-primary min-h-12 w-full justify-center text-sm sm:w-auto xl:hidden">Посмотреть схему →</button>
    </div>

    <div ref={layoutRef} className={`card scroll-mt-24 space-y-4 border-stone-200 bg-[#fffdf9] p-4 dark:border-slate-700 dark:bg-slate-900 sm:p-6 xl:col-start-2 xl:row-start-2 xl:block ${activeStage === "layout" ? "block" : "hidden"}`}><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-rose-700 dark:text-rose-300">Шаг 2 · живая схема</p><h2 className="mt-1 text-xl font-bold text-stone-950 dark:text-white">Плитка внутри бордюров</h2><p className="mt-1 text-sm text-stone-500 dark:text-slate-400">{result.rows} рядов · диагональю отмечены подрезки · серый контур показывает бордюр</p></div><div className="max-h-[680px] overflow-auto rounded-[1.25rem] border border-stone-200 bg-stone-100 p-1 shadow-inner dark:border-slate-700 dark:bg-slate-950 sm:p-3"><PavingSvg result={result} /></div><div className="grid gap-2 sm:grid-cols-2 xl:hidden"><button type="button" onClick={() => changeStage("parameters")} className="min-h-12 rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-stone-700 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-200">← Изменить параметры</button><button type="button" onClick={() => changeStage("result")} className="btn-primary min-h-12 w-full justify-center text-sm">Посмотреть результат →</button></div></div>

    <div ref={resultRef} className={`card scroll-mt-24 border-stone-200 bg-[#fffdf9] p-4 dark:border-slate-700 dark:bg-slate-900 sm:p-6 xl:col-start-3 xl:row-start-2 xl:block xl:sticky xl:top-20 ${activeStage === "result" ? "block" : "hidden"}`}><div className="rounded-2xl border border-rose-200 bg-gradient-to-br from-rose-50 to-amber-50 p-4 dark:border-rose-900/50 dark:from-rose-950/20 dark:to-amber-950/10"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-rose-800 dark:text-rose-300">Паспорт раскладки</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-stone-950 dark:text-white">Тротуарная плитка</h2><p className="mt-1 text-xs text-stone-600 dark:text-slate-400">Площадка {surfaceWidth.toLocaleString("ru-RU")} × {surfaceLength.toLocaleString("ru-RU")} мм · плитка {paverLength} × {paverWidth} мм</p></div><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-semibold text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300">Подрезки учтены</span></div></div><div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 p-4 dark:border-rose-800/60 dark:bg-rose-900/20"><p className="text-xs font-semibold uppercase tracking-wide text-rose-700 dark:text-rose-300">Элементов к покупке</p><p className="mt-1 text-4xl font-bold text-slate-950 dark:text-white">{result.purchasePavers}</p><p className="mt-1 text-xs text-slate-500">{result.basePavers} по раскладке + {result.reservePavers} закрытых в запас</p></div><div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-4 xl:grid-cols-2"><ToolMetric value={result.wholePavers} label="Целых на схеме" tone="emerald" /><ToolMetric value={result.cutPieces} label="Подрезанных деталей" tone="amber" /><ToolMetric value={`${result.geometricWastePercent}%`} label="Расчётный отход подрезки" /><ToolMetric value={`${result.input.jointMm} мм`} label="Шов" /></div><ToolNotes warnings={result.warnings} notes={result.notes} /><div className="mt-5 flex flex-col gap-2 border-t border-slate-100 pt-5 dark:border-slate-800">{calculatorHref && <Link href={calculatorHref} onClick={() => trackToolRelatedClick("raskladka-trotuarnoy-plitki", "paving-calculator")} className="btn-primary min-h-12 justify-center text-sm no-underline">Рассчитать основание и бордюр →</Link>}<SaveToProjectButton calcId="instrument-raskladka-trotuarnoy-plitki" calcTitle="Раскладка тротуарной плитки" slug="trotuarnaya-plitka" categorySlug="fasad" materials={materials} /></div><button type="button" onClick={() => changeStage("layout")} className="mt-4 min-h-11 w-full rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-stone-600 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-300 xl:hidden">← Вернуться к схеме</button></div>
  </div>;
}
