export const DEFAULT_YANDEX_METRIKA_COUNTER = "108155444";

export const YANDEX_METRIKA_COUNTER =
  process.env.NEXT_PUBLIC_YM_COUNTER?.trim() || DEFAULT_YANDEX_METRIKA_COUNTER;

export const YANDEX_METRIKA_COUNTER_ID = Number(YANDEX_METRIKA_COUNTER);
