export const DEFAULT_YANDEX_METRIKA_COUNTER = "108155444";

export const DEFAULT_GOOGLE_ANALYTICS_ID = "G-R0N1L7QDR3";

export const YANDEX_METRIKA_COUNTER =
  process.env.NEXT_PUBLIC_YM_COUNTER?.trim() || DEFAULT_YANDEX_METRIKA_COUNTER;

export const YANDEX_METRIKA_COUNTER_ID = Number(YANDEX_METRIKA_COUNTER);

export const GOOGLE_ANALYTICS_ID =
  process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID?.trim() || DEFAULT_GOOGLE_ANALYTICS_ID;
