import type { CalculatorDefinition } from "../types";
import { withSiteMetaTitle } from "../meta";
import { computeCanonicalRoofing } from "../../../../engine/roofing";
import roofingSpec from "../../../../configs/calculators/roofing-canonical.v1.json";
import defaultFactorTables from "../../../../configs/factor-tables.json";

const hideProjectArea = { key: "roofAreaMode", op: "eq" as const, value: 1 };
const hideProjectionArea = { key: "roofAreaMode", op: "eq" as const, value: 0 };
const hideWithoutRidge = { key: "ridgeProjectM", op: "eq" as const, value: 0 };
const hideWithoutValley = { key: "valleyProjectM", op: "eq" as const, value: 0 };
const hideWithoutEaves = { key: "eavesProjectM", op: "eq" as const, value: 0 };
const hideWithoutMembrane = { key: "membraneProjectAreaM2", op: "eq" as const, value: 0 };
const hideWithoutDeck = { key: "deckProjectAreaM2", op: "eq" as const, value: 0 };
const hideWithoutBatten = { key: "battenProjectLengthM", op: "eq" as const, value: 0 };
const hideWithoutCounterBatten = { key: "counterBattenProjectLengthM", op: "eq" as const, value: 0 };
const hideWithoutFasteners = { key: "fastenersProjectPcs", op: "eq" as const, value: 0 };
const hideWithoutSnowGuard = { key: "snowGuardProjectM", op: "eq" as const, value: 0 };
const hideWithoutTape = { key: "sealingTapeProjectM", op: "eq" as const, value: 0 };

export const roofingDef: CalculatorDefinition = {
  id: "roofing_unified",
  slug: "krovlya",
  title: "Калькулятор материалов кровли",
  h1: "Кровля — закупка материалов по проекту и фактическим фасовкам",
  description:
    "Переведите площадь скатов и готовую проектную ведомость в листы, упаковки, планки, рулоны, доски, крепёж и секции к покупке.",
  metaTitle: withSiteMetaTitle("Кровля: расчёт материалов по проекту"),
  metaDescription:
    "Бесплатный калькулятор материалов кровли: рассчитайте покрытие, доборные элементы, мембрану, основание, пиломатериал и крепёж по проектным количествам и реальным фасовкам.",
  category: "roofing",
  categorySlug: "krovlya",
  tags: [
    "кровля",
    "крыша",
    "металлочерепица",
    "профнастил",
    "битумная черепица",
    "материалы по проекту",
  ],
  popularity: 85,
  complexity: 3,
  fields: [
    {
      key: "roofAreaMode",
      label: "Как задана площадь кровли",
      type: "select",
      defaultValue: 0,
      options: [
        { value: 0, label: "Сумма площадей скатов из проекта или обмера" },
        { value: 1, label: "Простая крыша: проекция со свесами + уклон" },
      ],
      hint: "Для вальмовой, мансардной, многощипцовой и любой сложной крыши используйте только готовую сумму площадей скатов",
      group: "Площадь скатов",
    },
    {
      key: "projectSlopeAreaM2",
      label: "Суммарная площадь скатов",
      type: "number",
      unit: "м²",
      min: 1,
      max: 10000,
      step: 0.1,
      defaultValue: 100,
      hideIf: hideProjectArea,
      hint: "Площадь вместе со свесами, но без закупочного запаса",
      group: "Площадь скатов",
    },
    {
      key: "planProjectionAreaM2",
      label: "Горизонтальная проекция скатов со свесами",
      type: "number",
      unit: "м²",
      min: 1,
      max: 10000,
      step: 0.1,
      defaultValue: 80,
      hideIf: hideProjectionArea,
      hint: "Не площадь дома по стенам: карнизные и фронтонные свесы уже должны входить",
      group: "Площадь скатов",
    },
    {
      key: "slopeDeg",
      label: "Одинаковый уклон простых скатов",
      type: "number",
      unit: "°",
      min: 1,
      max: 75,
      step: 1,
      defaultValue: 30,
      hideIf: hideProjectionArea,
      group: "Площадь скатов",
    },
    {
      key: "roofingType",
      label: "Тип основного покрытия",
      type: "select",
      defaultValue: 0,
      options: [
        { value: 0, label: "Металлочерепица" },
        { value: 1, label: "Мягкая черепица (битумная)" },
        { value: 2, label: "Профнастил" },
        { value: 3, label: "Битумный волнистый лист" },
        { value: 4, label: "Хризотилцементный волнистый лист" },
        { value: 5, label: "Керамическая или цементно-песчаная черепица" },
      ],
      hint: "Тип меняет название покупной единицы, но не подставляет скрытые нормы производителя",
      group: "Основное покрытие",
    },
    {
      key: "primaryCoverageM2",
      label: "Полезная площадь одной покупной единицы",
      type: "number",
      unit: "м²",
      min: 0,
      max: 1000,
      step: 0.001,
      defaultValue: 1,
      hint: "Для листа, упаковки или одной черепицы — по маркировке выбранного товара с учётом штатных нахлёстов",
      group: "Основное покрытие",
    },
    {
      key: "primaryReservePercent",
      label: "Запас основного покрытия по раскладке",
      type: "number",
      unit: "%",
      min: 0,
      max: 50,
      step: 1,
      defaultValue: 10,
      hint: "Запас задаёт пользователь или проект; форма крыши не заменяется условным коэффициентом сложности",
      group: "Основное покрытие",
    },
    {
      key: "ridgeProjectM",
      label: "Длина коньковых элементов из ведомости",
      type: "number",
      unit: "м",
      min: 0,
      max: 10000,
      step: 0.1,
      defaultValue: 0,
      hint: "0 — не включать эту позицию",
      group: "Доборные элементы",
    },
    {
      key: "ridgeReservePercent",
      label: "Запас коньковых элементов",
      type: "number",
      unit: "%",
      min: 0,
      max: 30,
      step: 1,
      defaultValue: 5,
      hideIf: hideWithoutRidge,
      group: "Доборные элементы",
    },
    {
      key: "ridgeElementUsefulLengthM",
      label: "Полезная длина одного конькового элемента",
      type: "number",
      unit: "м",
      min: 0,
      max: 100,
      step: 0.01,
      defaultValue: 0,
      hideIf: hideWithoutRidge,
      hint: "Уже после вычета нахлёста по инструкции выбранной системы",
      group: "Доборные элементы",
    },
    {
      key: "valleyProjectM",
      label: "Длина ендовных элементов из ведомости",
      type: "number",
      unit: "м",
      min: 0,
      max: 10000,
      step: 0.1,
      defaultValue: 0,
      group: "Доборные элементы",
    },
    {
      key: "valleyReservePercent",
      label: "Запас ендовных элементов",
      type: "number",
      unit: "%",
      min: 0,
      max: 50,
      step: 1,
      defaultValue: 10,
      hideIf: hideWithoutValley,
      group: "Доборные элементы",
    },
    {
      key: "valleyElementUsefulLengthM",
      label: "Полезная длина одного ендовного элемента",
      type: "number",
      unit: "м",
      min: 0,
      max: 100,
      step: 0.01,
      defaultValue: 0,
      hideIf: hideWithoutValley,
      group: "Доборные элементы",
    },
    {
      key: "eavesProjectM",
      label: "Длина карнизных планок из ведомости",
      type: "number",
      unit: "м",
      min: 0,
      max: 10000,
      step: 0.1,
      defaultValue: 0,
      group: "Доборные элементы",
    },
    {
      key: "eavesReservePercent",
      label: "Запас карнизных планок",
      type: "number",
      unit: "%",
      min: 0,
      max: 30,
      step: 1,
      defaultValue: 5,
      hideIf: hideWithoutEaves,
      group: "Доборные элементы",
    },
    {
      key: "eavesElementUsefulLengthM",
      label: "Полезная длина одной карнизной планки",
      type: "number",
      unit: "м",
      min: 0,
      max: 100,
      step: 0.01,
      defaultValue: 0,
      hideIf: hideWithoutEaves,
      group: "Доборные элементы",
    },
    {
      key: "membraneProjectAreaM2",
      label: "Площадь кровельной мембраны из проекта",
      type: "number",
      unit: "м²",
      min: 0,
      max: 10000,
      step: 0.1,
      defaultValue: 0,
      hint: "Тип, слои, нахлёсты и вентиляционные зазоры должны быть определены проектом",
      group: "Мембрана и основание",
    },
    {
      key: "membraneReservePercent",
      label: "Запас мембраны",
      type: "number",
      unit: "%",
      min: 0,
      max: 50,
      step: 1,
      defaultValue: 15,
      hideIf: hideWithoutMembrane,
      group: "Мембрана и основание",
    },
    {
      key: "membraneRollCoverageM2",
      label: "Полезная площадь одного рулона мембраны",
      type: "number",
      unit: "м²",
      min: 0,
      max: 1000,
      step: 0.1,
      defaultValue: 0,
      hideIf: hideWithoutMembrane,
      hint: "По фактическому рулону и принятой схеме нахлёстов",
      group: "Мембрана и основание",
    },
    {
      key: "deckProjectAreaM2",
      label: "Площадь сплошного листового основания из проекта",
      type: "number",
      unit: "м²",
      min: 0,
      max: 10000,
      step: 0.1,
      defaultValue: 0,
      hint: "0 — не включать; толщину и шаг опор калькулятор не подбирает",
      group: "Мембрана и основание",
    },
    {
      key: "deckReservePercent",
      label: "Запас листового основания",
      type: "number",
      unit: "%",
      min: 0,
      max: 50,
      step: 1,
      defaultValue: 10,
      hideIf: hideWithoutDeck,
      group: "Мембрана и основание",
    },
    {
      key: "deckSheetAreaM2",
      label: "Площадь одного листа основания",
      type: "number",
      unit: "м²",
      min: 0,
      max: 100,
      step: 0.001,
      defaultValue: 0,
      hideIf: hideWithoutDeck,
      group: "Мембрана и основание",
    },
    {
      key: "battenProjectLengthM",
      label: "Длина одной позиции обрешётки из ведомости",
      type: "number",
      unit: "м",
      min: 0,
      max: 100000,
      step: 0.1,
      defaultValue: 0,
      hint: "Шаг, сечение и сорт принимает проект; разные позиции считайте отдельно",
      group: "Пиломатериал из проекта",
    },
    {
      key: "battenReservePercent",
      label: "Запас обрешётки на раскрой",
      type: "number",
      unit: "%",
      min: 0,
      max: 30,
      step: 1,
      defaultValue: 5,
      hideIf: hideWithoutBatten,
      group: "Пиломатериал из проекта",
    },
    {
      key: "battenBoardLengthM",
      label: "Длина покупной доски обрешётки",
      type: "number",
      unit: "м",
      min: 0,
      max: 20,
      step: 0.1,
      defaultValue: 0,
      hideIf: hideWithoutBatten,
      hint: "Общий метраж не заменяет карту раскроя",
      group: "Пиломатериал из проекта",
    },
    {
      key: "counterBattenProjectLengthM",
      label: "Длина одной позиции контробрешётки из ведомости",
      type: "number",
      unit: "м",
      min: 0,
      max: 100000,
      step: 0.1,
      defaultValue: 0,
      group: "Пиломатериал из проекта",
    },
    {
      key: "counterBattenReservePercent",
      label: "Запас контробрешётки на раскрой",
      type: "number",
      unit: "%",
      min: 0,
      max: 30,
      step: 1,
      defaultValue: 5,
      hideIf: hideWithoutCounterBatten,
      group: "Пиломатериал из проекта",
    },
    {
      key: "counterBattenBoardLengthM",
      label: "Длина покупного бруска контробрешётки",
      type: "number",
      unit: "м",
      min: 0,
      max: 20,
      step: 0.1,
      defaultValue: 0,
      hideIf: hideWithoutCounterBatten,
      group: "Пиломатериал из проекта",
    },
    {
      key: "fastenersProjectPcs",
      label: "Количество одной позиции крепежа из ведомости",
      type: "number",
      unit: "шт",
      min: 0,
      max: 1000000,
      step: 1,
      defaultValue: 0,
      hint: "Тип, размер, шаг и зоны крепления определяет проект или инструкция системы",
      group: "Крепёж и безопасность",
    },
    {
      key: "fastenersReservePercent",
      label: "Запас крепежа",
      type: "number",
      unit: "%",
      min: 0,
      max: 30,
      step: 1,
      defaultValue: 5,
      hideIf: hideWithoutFasteners,
      group: "Крепёж и безопасность",
    },
    {
      key: "fastenersPackagePcs",
      label: "Количество крепежа в упаковке",
      type: "number",
      unit: "шт",
      min: 0,
      max: 100000,
      step: 1,
      defaultValue: 0,
      hideIf: hideWithoutFasteners,
      group: "Крепёж и безопасность",
    },
    {
      key: "snowGuardProjectM",
      label: "Длина снегозадержания из проекта",
      type: "number",
      unit: "м",
      min: 0,
      max: 10000,
      step: 0.1,
      defaultValue: 0,
      hint: "Количество рядов и опор должно быть определено по нагрузкам и геометрии",
      group: "Крепёж и безопасность",
    },
    {
      key: "snowGuardReservePercent",
      label: "Запас снегозадержателей",
      type: "number",
      unit: "%",
      min: 0,
      max: 30,
      step: 1,
      defaultValue: 5,
      hideIf: hideWithoutSnowGuard,
      group: "Крепёж и безопасность",
    },
    {
      key: "snowGuardSectionUsefulLengthM",
      label: "Полезная длина одной секции снегозадержателя",
      type: "number",
      unit: "м",
      min: 0,
      max: 100,
      step: 0.01,
      defaultValue: 0,
      hideIf: hideWithoutSnowGuard,
      group: "Крепёж и безопасность",
    },
    {
      key: "sealingTapeProjectM",
      label: "Длина системной ленты из раскладки",
      type: "number",
      unit: "м",
      min: 0,
      max: 100000,
      step: 0.1,
      defaultValue: 0,
      hint: "Для стыков мембран и примыканий; 0 — не включать",
      group: "Герметизация",
    },
    {
      key: "sealingTapeReservePercent",
      label: "Запас системной ленты",
      type: "number",
      unit: "%",
      min: 0,
      max: 50,
      step: 1,
      defaultValue: 10,
      hideIf: hideWithoutTape,
      group: "Герметизация",
    },
    {
      key: "sealingTapeRollLengthM",
      label: "Длина одного рулона ленты",
      type: "number",
      unit: "м",
      min: 0,
      max: 1000,
      step: 0.1,
      defaultValue: 0,
      hideIf: hideWithoutTape,
      group: "Герметизация",
    },
  ],
  calculate(inputs) {
    return computeCanonicalRoofing(
      roofingSpec as never,
      inputs,
      defaultFactorTables.factors as never,
    );
  },
  formulaDescription: `
**Закупка материалов кровли по проекту:**

1. **Площадь скатов** — из проекта или обмера. Только для простой одно- или двухскатной крыши допустимо: проекция со свесами / cos(уклона).
2. **Основное покрытие** — площадь скатов × явный запас / полезная площадь реального листа, упаковки или одной черепицы.
3. **Доборные и сопутствующие позиции** — количество из готовой проектной ведомости × явный запас / полезная длина, площадь или фасовка товара.
4. **К покупке** — всегда округление вверх до целых листов, упаковок, рулонов, досок, секций или других покупных единиц.
  `,
  howToUse: [
    "Возьмите сумму площадей скатов из проекта или обмера; для простой крыши можно использовать проекцию со свесами и одинаковый уклон",
    "Выберите покрытие и перенесите полезную площадь одной покупной единицы из документации товара",
    "Добавьте только те доборные и сопутствующие позиции, количества которых уже определены проектом",
    "Сверьте результат к покупке с раскладкой, картой раскроя и спецификацией кровельной системы",
  ],
  expertTips: [
    {
      title: "Полезная площадь важнее полной",
      content:
        "Размер листа на ценнике не равен площади покрытия. Для закупки нужна полезная площадь после штатных боковых и продольных нахлёстов конкретного профиля.",
      author: "Проектная граница калькулятора",
    },
    {
      title: "Один метраж не заменяет раскрой",
      content:
        "Планки и пиломатериал разных длин и сечений считайте отдельными позициями. Иначе округление общего метража может скрыть нехватку цельных элементов.",
      author: "Практика комплектации",
    },
  ],
  faq: [
    {
      question: "Почему калькулятор не подбирает стропила и шаг обрешётки?",
      answer:
        "Потому что эти решения зависят от снеговых и ветровых нагрузок, пролётов, опор, материала, выбранного покрытия и узлов. Их определяет проект; калькулятор переводит уже принятую ведомость в покупные единицы.",
    },
    {
      question: "Можно ли считать площадь крыши по площади дома?",
      answer:
        "Только для простой одно- или двухскатной крыши с одинаковым уклоном и только если горизонтальная проекция уже включает свесы. Для вальмовой, мансардной, многощипцовой крыши и скатов с разными уклонами нужна сумма площадей из проекта или обмера.",
    },
    {
      question: "Почему крепёж и снегозадержатели не появляются автоматически?",
      answer:
        "Универсальная норма по квадратному метру не учитывает профиль, зоны крепления, ветровые усилия, длину ската и число рядов. Введите проектное количество конкретной позиции и её фактическую фасовку.",
    },
  ],
  seoContent: {
    descriptionHtml: `
<h2>Что считает калькулятор материалов кровли</h2>
<p>Калькулятор переводит готовую площадь скатов и проектные количества в покупные единицы выбранных товаров. Он показывает точную потребность, явный запас, округление по фасовке и остаток.</p>
<p><strong>Основное покрытие:</strong> N = &lceil;S &times; (1 + Z / 100) / S<sub>полезная</sub>&rceil;, где S — площадь скатов, Z — заданный запас, S<sub>полезная</sub> — полезная площадь одного листа, упаковки или одной черепицы.</p>

<h2>Граница расчёта</h2>
<p>СП 17.13330.2017 распространяется на проектирование кровель разных систем, СП 20.13330.2016 — на нагрузки, а СП 64.13330.2017 — на расчёт деревянных конструкций. Поэтому калькулятор не назначает стропила, прогоны, обрешётку, кровельный пирог, крепёж или снегозадержание по одной площади крыши.</p>
<p>Полезные размеры и фасовки берутся из маркировки и инструкции конкретного товара. Это особенно важно для металлочерепицы, профнастила, битумной и штучной черепицы: одинаковая полная площадь может давать разную полезную площадь покрытия.</p>

<h2>Как получить надёжный результат</h2>
<ol>
  <li>Для сложной крыши перенесите сумму площадей всех скатов из проекта.</li>
  <li>Введите полезную площадь одной покупной единицы покрытия.</li>
  <li>Добавьте коньки, ендовы, карнизы, мембрану, основание, пиломатериал, крепёж и снегозадержатели только по готовой ведомости.</li>
  <li>Разделите разные типоразмеры на отдельные расчёты и сверьте результат с раскладкой.</li>
</ol>
    `,
    faq: [
      {
        question: "Что означает MIN, REC и MAX?",
        answer:
          "Сценарии относятся только к основному покрытию: MIN — без запаса, REC — с заданным запасом, MAX — с запасом не меньше 15%. Остальные позиции используют собственные запасы из формы.",
      },
      {
        question: "Что вводить для мягкой черепицы?",
        answer:
          "Введите площадь покрытия одной упаковки выбранной коллекции. Подкладочный ковёр, мастику, основание, аэраторы и крепёж добавляйте по проекту и системной инструкции; для детальной комплектации также доступен отдельный калькулятор мягкой кровли.",
      },
    ],
  },
};
