"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { CommerceOrder, CommercePublicState, CommerceUser } from "@/lib/commerce/types";
import { trackCommerceEvent } from "@/lib/analytics";
import ProOffer from "@/components/commerce/ProOffer";
import { PROJECT_ESTIMATE_NAME } from "@/lib/commerce/product-copy";
type Me = { user: CommerceUser | null; state: CommercePublicState; access: { pro: boolean; proUntil: number; pack: boolean }; subscription: { auto_renew: boolean } | null; projects: Array<{id:string;name:string;local_id:string}>; orders: CommerceOrder[]; documents: Array<{id:string;format:string;created_at:number;name:string}> };
const ruState: Record<string,string> = {pending:"ожидает оплаты",paid:"оплачен",canceled:"отменён",partially_refunded:"частично возвращён",refunded:"возвращён"};
const field = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-slate-950 shadow-sm outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20 dark:border-slate-600 dark:bg-slate-900 dark:text-white";
export function CommerceLogin({onSignedIn}:{onSignedIn?:()=>void}) {
  const [email,setEmail]=useState(""); const [challenge,setChallenge]=useState(""); const [code,setCode]=useState("");
  const [localCode,setLocalCode]=useState<string>(); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit() {
    setBusy(true); setError("");
    try {
      const response=await fetch(`/api/commerce/auth/${challenge?"verify":"request"}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(challenge?{challenge,code}:{email})});
      const body=await response.json(); if(!response.ok) throw new Error(body.error??"Не удалось выполнить вход");
      if(challenge) onSignedIn?.(); else {setChallenge(body.challenge);setLocalCode(body.localCode);}
    } catch(cause) {setError(cause instanceof Error?cause.message:"Нет связи с сервером");} finally {setBusy(false);}
  }
  return <section className="max-w-md rounded-2xl border border-slate-300 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-950"><p className="text-sm font-medium text-orange-700 dark:text-orange-300">Ваши проекты и документы</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Вход в кабинет</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Почта нужна для доступа к вашим проектам и покупкам. Рекламных рассылок нет.</p>
    <form onSubmit={e=>{e.preventDefault();void submit();}}>{!challenge?<label className="mt-4 block text-sm">Электронная почта<input className={field} type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label>:<><p className="mt-3 break-words text-sm">Код для {email}</p><label className="mt-3 block text-sm">Шестизначный код<input className={field} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value)}/></label>{localCode&&<p className="mt-2 text-xs text-amber-800 dark:text-amber-300">Локальная проверка без писем и денег. Тестовый код: <b>{localCode}</b></p>}</>}
    <button disabled={busy} className="btn-primary mt-3" type="submit">{busy?"Подождите…":challenge?"Войти":"Получить код"}</button>{challenge&&<button disabled={busy} className="ml-3 text-sm underline" type="button" onClick={()=>{setChallenge("");setCode("");setError("");}}>Другой адрес / новый код</button>}</form>
    <p className="mt-3 text-xs text-slate-500">Обработка почты для входа описана в <Link className="underline" href="/politika-konfidencialnosti/">политике конфиденциальности</Link>.</p>{error&&<p role="alert" className="mt-2 text-sm text-red-700 dark:text-red-300">{error}</p>}</section>;
}
export default function AccountPanel() {
  const [data,setData]=useState<Me|null>(null);const [loading,setLoading]=useState(true);const [offer,setOffer]=useState(false);const [renew,setRenew]=useState(false);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const r=await fetch("/api/commerce/me");const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);}catch{setNotice("Кабинет сейчас недоступен. Повторите загрузку.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function action(path:string,body:Record<string,unknown>={}) {setBusy(true);setNotice("");try{const r=await fetch(`/api/commerce/${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error??"Действие не выполнено");if(b.paymentUrl)location.href=b.paymentUrl;else await load();}catch(cause){setNotice(cause instanceof Error?cause.message:"Нет связи с сервером");}finally{setBusy(false);}}
  if(loading)return <main className="page-container py-12">Загружаем кабинет…</main>;
  if(!data)return <main className="page-container py-12"><p role="alert">{notice}</p><button className="btn-secondary mt-3" onClick={()=>void load()}>Повторить</button></main>;
  if(!data.state.enabled)return <main className="page-container py-12"><h1 className="text-2xl font-bold">Кабинет покупок пока не подключён</h1><p className="mt-3">Проекты на устройстве, расчёты и бесплатный экспорт доступны.</p><Link className="btn-primary mt-4" href="/proekty/">Мои проекты</Link></main>;
  if(!data.user)return <main className="page-container py-12"><CommerceLogin onSignedIn={load}/></main>;
  const {state}=data;
  return <main className="page-container max-w-4xl py-8"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 pb-5 dark:border-slate-700"><div><p className="text-sm font-medium text-orange-700 dark:text-orange-300">Кабинет проекта</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Кабинет</h1><p className="break-all text-sm text-slate-500">{data.user.email}</p></div><button disabled={busy} className="btn-secondary" onClick={()=>void action("auth/logout")}>Выйти</button></div>
    {state.mode!=="live"&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950 dark:text-amber-200">{state.mode==="local"?"Локальный симулятор: деньги не списываются. Это ещё не проверка в Robokassa.":"Тестовый режим Robokassa: реальная покупка не выполняется."}</p>}{notice&&<p role="alert" className="mt-3 text-red-700 dark:text-red-300">{notice}</p>}
    <ProOffer state={state} access={data.access} subscription={data.subscription} accepted={offer} recurring={renew} busy={busy} onAcceptedChange={setOffer} onRecurringChange={setRenew} onPay={()=>{trackCommerceEvent("commerce_checkout_start",{product:"pro_month"});void action("orders",{kind:"pro_month",expectedAmount:state.proPriceKopecks,acceptedOffer:state.offerVersion,recurring:renew});}} onCancel={()=>void action("subscription/cancel")}/>
    <section className="card mt-5 p-5"><h2 className="font-bold">Проекты в кабинете</h2>{data.projects.length?data.projects.map(p=><Link key={p.id} className="mt-2 block break-words text-accent-700 dark:text-accent-300" href={`/proekty/${encodeURIComponent(p.local_id)}/zakupka/?cloud=${p.id}`}>{p.name}</Link>):<p className="mt-2 text-sm text-slate-500">Откройте локальную смету и сохраните её в кабинет перед покупкой.</p>}<Link className="mt-3 inline-block text-sm underline" href="/proekty/">Проекты на этом устройстве</Link></section>
    <section className="card mt-5 p-5"><h2 className="text-lg font-semibold">Заказы и покупки</h2>{!data.orders.length&&<p className="mt-2 text-sm text-slate-500">Покупок пока нет.</p>}{data.orders.map(o=>{const project=data.projects.find(p=>p.id===o.project_id);return <div key={o.id} className="mt-3 border-t pt-3 text-sm"><Link className="underline" href={`/oplata/${o.id}/`}>{o.kind==="pro_month"?"PRO на месяц":PROJECT_ESTIMATE_NAME} · {(o.amount/100).toLocaleString("ru-RU")} ₽</Link><span> · {ruState[o.state]??o.state}</span><p className="mt-1 text-xs text-slate-500">{new Date(Number(o.created_at)).toLocaleDateString("ru-RU")}{project?` · ${project.name}`:""}</p>{o.refunded>0&&<p>Возвращено {(o.refunded/100).toLocaleString("ru-RU")} ₽</p>}</div>})}</section>
    <section className="card mt-5 p-5"><h2 className="text-lg font-semibold">Сохранённые документы</h2><p className="mt-1 text-sm text-slate-500">Созданные во время PRO документы доступны и после окончания подписки, если оплата не возвращена полностью.</p>{!data.documents.length&&<p className="mt-2 text-sm">Пока нет документов. Создайте комплект на странице проекта.</p>}{data.documents.map(d=><a key={d.id} className="mt-2 block text-accent-700 dark:text-accent-300" href={`/api/commerce/documents/${d.id}`}>{d.name} · {d.format.toUpperCase()} · {new Date(Number(d.created_at)).toLocaleDateString("ru-RU")}</a>)}</section>
    {data.user.admin&&<Link className="mt-5 block text-sm underline" href="/upravlenie/monetizatsiya/">Управление монетизацией →</Link>}</main>;
}
