"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { CommerceMode, CommerceOrder, CommerceSettings, MaterialOffer } from "@/lib/commerce/types";

type Sale = { provider: string; reference: string; state: "pending" | "approved" | "rejected" | "paid"; commission: number; report_reference: string };
type Payload = { settings: CommerceSettings; orders: CommerceOrder[]; metrics: { event: string; count: number }[]; financial: { gross: number; refunds: number; net: number }; affiliateSales: Sale[]; mode: CommerceMode };
const emptyOffer: MaterialOffer = { id: "", title: "", provider: "sponsor", url: "", calculatorSlugs: [], suitability: "", limitations: "", advertiser: "", advertiserInn: "", erid: "", contractReference: "", reviewedAt: "", expiresAt: "", enabled: false };
const eventLabel: Record<string, string> = { purchase_started: "Начатые оплаты", purchase_confirmed: "Подтверждённые оплаты", refund_confirmed: "Подтверждённые возвраты", document_generated: "Созданные документы", affiliate_click: "Переходы к партнёрам", subscription_canceled: "Отмены автопродления", renewal_initiated: "Запущенные продления" };
const toggleLabel = { checkoutEnabled: "Разрешить оформление оплаты", proEnabled: "Включить PRO", recurringEnabled: "Разрешить автопродление", offersEnabled: "Показывать рекламные предложения", proAiEnabled: "Включить помощника PRO", legalApproved: "Юридические условия проверены" } as const;
const rub = (n: number) => new Intl.NumberFormat("ru-RU", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n / 100);
const kp = (s: string) => Math.round(Number(s.replace(",", ".")) * 100);
const message = (body: unknown, fallback: string) => body && typeof body === "object" && "error" in body && typeof body.error === "string" ? body.error : fallback;
const storageKey = (orderId: string, amount: number) => `masterok:refund:${orderId}:${amount}`;

export default function CommerceAdmin() {
  const [data, setData] = useState<Payload | null>(null); const [state, setState] = useState<"loading" | "unauthenticated" | "forbidden" | "unavailable" | "ready">("loading");
  const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [csv, setCsv] = useState("");
  const [refund, setRefund] = useState({ orderId: "", rubles: "", refundId: "", result: "" });
  const load = useCallback(async () => { setState("loading"); try { const r = await fetch("/api/commerce/admin"); if (r.status === 401) return setState("unauthenticated"); if (r.status === 403) return setState("forbidden"); if (!r.ok) return setState("unavailable"); setData(await r.json() as Payload); setState("ready"); } catch { setState("unavailable"); } }, []);
  useEffect(() => { void load(); }, [load]);
  const run = async (name: string, work: () => Promise<void>) => { if (busy) return; setBusy(name); setNotice(null); try { await work(); } catch (e) { setNotice(e instanceof Error ? e.message : "Не удалось выполнить действие."); } finally { setBusy(null); } };
  const update = <K extends keyof CommerceSettings>(key: K, value: CommerceSettings[K]) => setData((v) => v ? { ...v, settings: { ...v.settings, [key]: value } } : v);
  const save = () => void run("settings", async () => { if (!data) return; const r = await fetch("/api/commerce/admin/settings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data.settings) }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(message(b, r.status === 409 ? "Настройки уже изменены. Перезагрузите страницу." : "Не удалось сохранить настройки.")); setNotice("Настройки сохранены."); await load(); });
  const importSales = () => void run("sales", async () => { const rows = csv.split(/\r?\n/).map((x) => x.trim()).filter(Boolean).map((line, i) => { const [provider = "", reference = "", state = "", commissionRub = "", reportReference = ""] = line.split(";").map((x) => x.trim()); const commission = Number(commissionRub.replace(",", ".")); if (!Number.isFinite(commission)) throw new Error(`Строка ${i + 1}: укажите вознаграждение в рублях числом.`); return { provider, reference, state, commissionRub: commission, reportReference }; }); if (!rows.length) throw new Error("Добавьте хотя бы одну строку отчёта."); const r = await fetch("/api/commerce/admin/sales", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ rows }) }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(message(b, "Не удалось импортировать отчёт.")); setCsv(""); setNotice("Отчёт импортирован."); await load(); });
  const requestRefund = () => void run("refund", async () => { const amount = kp(refund.rubles); if (!refund.orderId || !Number.isInteger(amount) || amount <= 0) throw new Error("Укажите заказ и точную сумму возврата."); const key = storageKey(refund.orderId, amount); const idempotencyKey = sessionStorage.getItem(key) ?? crypto.randomUUID(); const r = await fetch("/api/commerce/admin/refund", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderId: refund.orderId, amountKopecks: amount, idempotencyKey }) }); const b = await r.json().catch(() => null) as { refundId?: string; state?: string } | null; if (!r.ok) throw new Error(message(b, "Сервер отклонил возврат.")); const id = b?.refundId ?? ""; const status = b?.state ?? "unknown"; setRefund((v) => ({ ...v, refundId: id, result: status })); if (status === "finished") { sessionStorage.removeItem(key); await load(); } else sessionStorage.setItem(key, idempotencyKey); setNotice(`Возврат ${status}. ID: ${id}`); });
  const checkRefund = () => void run("check", async () => { if (!refund.refundId) throw new Error("Укажите ID возврата."); const r = await fetch("/api/commerce/admin/refund-check", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ refundId: refund.refundId }) }); const b = await r.json().catch(() => null) as { state?: string } | null; if (!r.ok) throw new Error(message(b, "Проверить статус пока не удалось.")); const result = b?.state ?? "unknown"; setRefund((v) => ({ ...v, result })); setNotice(`Статус возврата: ${result}.`); if (result === "finished") await load(); });
  const reconcile = (orderId: string) => void run(`reconcile:${orderId}`, async () => { const r = await fetch("/api/commerce/admin/reconcile", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderId }) }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(message(b, "Не удалось сверить заказ с Robokassa.")); setNotice("Заказ сверён с Robokassa."); await load(); });
  if (state === "loading") return <main className="page-container py-12">Загружаем управление…</main>;
  if (state === "unauthenticated") return <main className="page-container py-12"><h1 className="text-2xl font-bold">Требуется вход</h1><Link href="/kabinet/" className="btn-primary mt-4">Войти</Link></main>;
  if (state === "forbidden") return <main className="page-container py-12"><h1 className="text-2xl font-bold">Нет прав доступа</h1></main>;
  if (state === "unavailable" || !data) return <main className="page-container py-12"><h1 className="text-2xl font-bold">Управление временно недоступно</h1><button className="btn-secondary mt-4" onClick={() => void load()}>Повторить</button></main>;
  const s = data.settings; const approved = data.affiliateSales.filter((x) => x.state === "approved").reduce((n, x) => n + Number(x.commission), 0); const paid = data.affiliateSales.filter((x) => x.state === "paid").reduce((n, x) => n + Number(x.commission), 0);
  return <main className="page-container max-w-5xl py-8 sm:py-12"><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Управление монетизацией</h1><p className="text-sm text-slate-500">Режим: <b>{data.mode === "local" ? "локальная симуляция" : data.mode}</b>. {data.mode === "local" ? "Реальные оплаты и запросы к провайдеру не выполняются." : "Оплаты включаются только серверной конфигурацией."}</p></div><button className="btn-primary" disabled={!!busy} onClick={save}>{busy === "settings" ? "Сохраняем…" : "Сохранить настройки"}</button></header>{notice && <p role="status" className="mt-4 rounded-xl bg-slate-100 p-3 text-sm">{notice}</p>}
    <section className="mt-6 grid gap-3 sm:grid-cols-3">{[["Подтверждённые оплаты", data.financial.gross], ["Возвраты", data.financial.refunds], ["Оплаты за вычетом возвратов", data.financial.net]].map(([l, n]) => <Card key={String(l)} label={String(l)} value={`${rub(Number(n))} ₽`} />)}</section>
    <section className="card mt-6 p-5"><h2 className="font-bold">События</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{data.metrics.map((x) => <Card key={x.event} label={eventLabel[x.event] ?? x.event} value={String(x.count)} />)}{!data.metrics.length && <p className="text-sm text-slate-500">Событий пока нет.</p>}</div></section>
    <section className="card mt-6 p-5"><h2 className="font-bold">Продукты и ИИ</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{([['Стоимость набора, ₽','packPriceKopecks'],['Стоимость PRO, ₽','proPriceKopecks'],['Бесплатных вопросов Михалычу в неделю','freeAiWeeklyRequests'],['Вопросов Михалычу и помощнику PRO в месяц','proAiRequests'],['Бюджет ИИ, коп.','proAiBudgetKopecks'],['Вход ИИ, коп. за млн токенов','aiInputKopecksPerMillion'],['Выход ИИ, коп. за млн токенов','aiOutputKopecksPerMillion']] as const).map(([l,k]) => <label key={k} className="text-sm">{l}<input className="mt-1 w-full rounded border p-2" value={k.includes("Price") ? rub(s[k] as number) : (s[k] ?? 5) as number} onChange={(e) => update(k, k.includes("Price") ? kp(e.target.value) : Number(e.target.value))} /></label>)}</div><div className="mt-3 flex flex-wrap gap-4">{(Object.keys(toggleLabel) as Array<keyof typeof toggleLabel>).map((k) => <label key={k} className="text-sm"><input type="checkbox" checked={s[k]} onChange={(e) => update(k, e.target.checked)} /> {toggleLabel[k]}</label>)}</div><label className="mt-3 block text-sm">Дата подтверждения ставок ИИ<input type="date" className="mt-1 block rounded border p-2" value={s.aiPriceCheckedAt.slice(0, 10)} onChange={(e) => update("aiPriceCheckedAt", e.target.value)} /></label></section>
    <section className="card mt-6 p-5"><h2 className="font-bold">Реквизиты и версия условий</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{([['sellerName','Наименование продавца'],['sellerInn','ИНН продавца'],['supportEmail','Почта поддержки'],['offerVersion','Версия условий']] as const).map(([k,l]) => <label key={k} className="text-sm">{l}<input className="mt-1 w-full rounded border p-2" value={s[k]} onChange={(e) => update(k,e.target.value)} /></label>)}</div></section>
    <section className="card mt-6 p-5"><h2 className="font-bold">Рекламные предложения</h2><button className="btn-secondary mt-2" onClick={() => update("offers", [...s.offers, { ...emptyOffer }])}>Добавить предложение</button>{s.offers.map((offer, index) => <Offer key={index} offer={offer} onChange={(patch) => update("offers", s.offers.map((x, i) => i === index ? { ...x, ...patch } : x))} onRemove={() => update("offers",s.offers.filter((_,i) => i !== index))} />)}</section>
    <section className="card mt-6 p-5"><h2 className="font-bold">Партнёрские продажи</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><Card label="Продажи в отчётах" value={String(data.affiliateSales.length)} /><Card label="Подтверждённое вознаграждение" value={`${rub(approved)} ₽`} /><Card label="Выплаченное вознаграждение" value={`${rub(paid)} ₽`} /></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th>Источник</th><th>Продажа</th><th>Статус</th><th>Вознаграждение</th><th>Основание отчёта</th></tr></thead><tbody>{data.affiliateSales.map((x) => <tr key={`${x.provider}:${x.reference}`} className="border-t"><td className="py-2">{x.provider}</td><td>{x.reference}</td><td>{x.state}</td><td>{rub(Number(x.commission))} ₽</td><td>{x.report_reference}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-slate-500">Строка: источник; номер продажи; pending|approved|rejected|paid; вознаграждение в рублях; ссылка или номер отчёта.</p><textarea className="mt-2 min-h-28 w-full rounded border p-2 font-mono text-xs" value={csv} onChange={(e) => setCsv(e.target.value)} /><button className="btn-secondary mt-2" disabled={!!busy} onClick={importSales}>{busy === "sales" ? "Импортируем…" : "Импортировать отчёт"}</button></section>
    <section className="card mt-6 p-5"><h2 className="font-bold">Заказы и возвраты</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th>Заказ</th><th>Продукт</th><th>Сумма</th><th>Статус</th><th></th></tr></thead><tbody>{data.orders.map((x) => <tr key={x.id} className="border-t"><td className="py-2 break-all">{x.id}</td><td>{x.kind === "pro_month" ? "PRO на месяц" : "Пакет документов"}</td><td>{rub(x.amount)} ₽</td><td>{x.state}</td><td>{data.mode === "live" && <button className="text-accent-700 underline disabled:opacity-50" disabled={!!busy} onClick={() => reconcile(x.id)}>{busy === `reconcile:${x.id}` ? "Сверяем…" : "Сверить с Robokassa"}</button>}</td></tr>)}</tbody></table></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><label className="text-sm">ID заказа<input className="mt-1 w-full rounded border p-2" value={refund.orderId} onChange={(e) => setRefund({...refund,orderId:e.target.value})}/></label><label className="text-sm">Сумма возврата, ₽<input className="mt-1 w-full rounded border p-2" value={refund.rubles} onChange={(e) => setRefund({...refund,rubles:e.target.value})}/></label><button className="btn-secondary self-end" disabled={!!busy} onClick={requestRefund}>{busy === "refund" ? "Отправляем…" : "Запросить возврат"}</button></div><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><label className="text-sm">ID возврата для проверки<input className="mt-1 w-full rounded border p-2" value={refund.refundId} onChange={(e) => setRefund({...refund,refundId:e.target.value})}/></label><button className="btn-secondary self-end" disabled={!!busy} onClick={checkRefund}>{busy === "check" ? "Проверяем…" : "Проверить статус"}</button></div>{refund.result && <p className="mt-3 text-sm">Последний возврат: <b>{refund.refundId}</b>, статус: <b>{refund.result}</b>.</p>}</section>
  </main>;
}
function Card({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-900"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>; }
function Offer({ offer, onChange, onRemove }: { offer: MaterialOffer; onChange: (p: Partial<MaterialOffer>) => void; onRemove: () => void }) { const fields = [['id','Идентификатор'],['title','Название'],['url','Ссылка'],['suitability','Когда подходит'],['limitations','Ограничения'],['advertiser','Рекламодатель'],['advertiserInn','ИНН рекламодателя'],['erid','ERID'],['contractReference','Договор'],['reviewedAt','Проверено'],['expiresAt','Действует до']] as const; return <fieldset className="mt-4 rounded-xl border p-3"><div className="grid gap-2 sm:grid-cols-2">{fields.map(([k,l]) => <label key={k} className="text-xs">{l}<input className="mt-1 w-full rounded border p-1.5" value={offer[k]} onChange={(e) => onChange({[k]:e.target.value})}/></label>)}<label className="text-xs">Источник<select className="mt-1 w-full rounded border p-1.5" value={offer.provider} onChange={(e) => onChange({provider:e.target.value as MaterialOffer["provider"]})}><option value="sponsor">Спонсор</option><option value="lemanapro">Лемана ПРО</option><option value="yandex_market">Яндекс Маркет</option></select></label><label className="text-xs">Калькуляторы через запятую<input className="mt-1 w-full rounded border p-1.5" value={offer.calculatorSlugs.join(",")} onChange={(e) => onChange({calculatorSlugs:e.target.value.split(",").map((x) => x.trim()).filter(Boolean)})}/></label></div><label className="mt-2 block text-xs"><input type="checkbox" checked={offer.enabled} onChange={(e) => onChange({enabled:e.target.checked})}/> Показывать предложение</label><button className="mt-2 text-xs text-red-600" onClick={onRemove}>Удалить предложение</button></fieldset>; }
