"use client";

import { useCallback, useEffect, useState } from "react";
import type { ProjectDocumentInput } from "@/lib/commerce/document-types";
type Template = { id?: string; name: string; payload: Pick<ProjectDocumentInput, "works" | "parties" | "terms"> };
type Version = { id: string; created_at: number | string; payload: ProjectDocumentInput };
type Change = { name: string; unit?: string; before: number | null; after: number | null; oldPrice: number | null; newPrice: number | null };
interface Props { cloudId?: string; enabled: boolean; aiAvailable?: boolean; document?: ProjectDocumentInput; onDocumentChange?: (next: ProjectDocumentInput) => void; onSave: () => Promise<boolean>; }
const date = (value: number | string) => { const n = typeof value === "string" ? Number(value) : value; return Number.isFinite(n) ? new Date(n).toLocaleString("ru-RU") : "Дата версии неизвестна"; };

export default function ProjectProTools({ cloudId, enabled, aiAvailable = false, document, onDocumentChange, onSave }: Props) {
  const [templates, setTemplates] = useState<Template[]>([]); const [versions, setVersions] = useState<Version[]>([]); const [templateName, setTemplateName] = useState(""); const [beforeId, setBeforeId] = useState(""); const [afterId, setAfterId] = useState(""); const [changes, setChanges] = useState<Change[]>([]); const [totals, setTotals] = useState<{ before: number; after: number } | null>(null); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState<string | null>(null);
  const loadVersions = useCallback(async () => { if (!cloudId) return; const r = await fetch(`/api/commerce/projects/${encodeURIComponent(cloudId)}/versions`); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(b?.error ?? "Не удалось загрузить версии."); setVersions(b?.versions ?? []); }, [cloudId]);
  const load = useCallback(async () => { if (!cloudId) return; const [t] = await Promise.all([fetch("/api/commerce/templates"), loadVersions()]); const b = await t.json().catch(() => null); if (!t.ok) throw new Error(b?.error ?? "Не удалось загрузить шаблоны."); setTemplates(b?.templates ?? []); }, [cloudId, loadVersions]);
  useEffect(() => { if (enabled && cloudId) void load().catch((e) => setNotice(e instanceof Error ? e.message : "Не удалось загрузить PRO-инструменты.")); }, [enabled, cloudId, load]);
  const run = async (name: string, fn: () => Promise<void>) => { if (busy) return; setBusy(name); setNotice(""); try { await fn(); } catch (e) { setNotice(e instanceof Error ? e.message : "Не удалось выполнить действие."); } finally { setBusy(null); } };
  if (!enabled || !cloudId || !document || !onDocumentChange) return null;
  const apply = (t: Template) => { if (!confirm("Шаблон заменит работы, данные подрядчика и условия. Материалы и заказчик останутся без изменений.")) return; onDocumentChange({ ...document, works: t.payload.works, terms: t.payload.terms, parties: { ...document.parties, contractor: t.payload.parties?.contractor } }); setNotice("Шаблон применён. Проверьте объёмы работ."); };
  const saveTemplate = () => void run("template", async () => { if (!templateName.trim()) throw new Error("Укажите название шаблона."); if (!(await onSave())) throw new Error("Сначала сохраните проект без ошибок."); const r = await fetch("/api/commerce/templates", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: cloudId, name: templateName.trim() }) }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(b?.error ?? "Не удалось сохранить шаблон."); setTemplateName(""); setNotice("Шаблон сохранён."); await load(); });
  const saveVersion = () => void run("version", async () => { if (!(await onSave())) throw new Error("Проект не сохранён. Исправьте данные и повторите."); await loadVersions(); setNotice("Новая версия сохранена и загружена в список."); });
  const compare = () => void run("compare", async () => { if (!beforeId || !afterId || beforeId === afterId) throw new Error("Выберите две разные версии."); const r = await fetch(`/api/commerce/projects/${encodeURIComponent(cloudId)}/compare`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ beforeId, afterId }) }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(b?.error ?? "Не удалось сравнить версии."); setChanges(b?.changes ?? []); setTotals({ before: Number(b?.beforeTotal?.knownGrandTotal ?? 0), after: Number(b?.afterTotal?.knownGrandTotal ?? 0) }); });
  const ask = () => void run("ai", async () => { const text = question.trim(); if (!text || text.length > 1000) throw new Error("Вопрос — от 1 до 1000 символов."); if (!(await onSave())) throw new Error("Сначала сохраните проект без ошибок."); const r = await fetch("/api/commerce/ai", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: cloudId, message: text }) }); const b = await r.json().catch(() => null); if (!r.ok) throw new Error(b?.error ?? "Михалыч пока не ответил."); setAnswer(b?.answer ?? "Ответ не получен."); });
  return <section className="mt-5 min-w-0 border-t border-slate-200 pt-4 dark:border-slate-700"><h3 className="font-bold">PRO-инструменты</h3>{notice && <p role="status" className="mt-2 text-sm text-amber-700 dark:text-amber-300">{notice}</p>}
    <div className="mt-3 min-w-0 rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-sm font-semibold">Подрядчик</p><div className="mt-2 grid min-w-0 gap-2 sm:grid-cols-3">{([['name','Организация подрядчика'],['contact','Контакт подрядчика'],['details','Реквизиты подрядчика']] as const).map(([key,label]) => <input key={key} aria-label={label} className="min-w-0 rounded border p-2 dark:bg-slate-900" placeholder={label} value={document.parties?.contractor?.[key] ?? ""} onChange={(e) => onDocumentChange({ ...document, parties: { ...document.parties, contractor: { ...document.parties?.contractor, [key]: e.target.value } } })}/>)}</div></div>
    <div className="mt-4 min-w-0"><p className="text-sm font-semibold">Шаблоны</p>{templates.map((t) => <button key={t.id ?? t.name} className="mr-2 mt-2 rounded-lg border px-3 py-2 text-sm" onClick={() => apply(t)}>{t.name}</button>)}<div className="mt-2 grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><input aria-label="Название шаблона" className="min-w-0 rounded border p-2 dark:bg-slate-900" value={templateName} onChange={(e) => setTemplateName(e.target.value)} placeholder="Название шаблона"/><button className="btn-secondary" disabled={!!busy} onClick={saveTemplate}>{busy === "template" ? "Сохраняем…" : "Сохранить шаблон"}</button></div></div>
    <div className="mt-4 min-w-0"><p className="text-sm font-semibold">Версии проекта</p><button className="btn-secondary mt-2" disabled={!!busy} onClick={saveVersion}>{busy === "version" ? "Сохраняем…" : "Сохранить новую версию"}</button><div className="mt-2 grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]"><select aria-label="Версия до" className="min-w-0 rounded border p-2 dark:bg-slate-900" value={beforeId} onChange={(e) => setBeforeId(e.target.value)}><option value="">Версия до</option>{versions.map((v) => <option key={v.id} value={v.id}>{v.payload.project.version ? `Версия ${v.payload.project.version} · ` : ""}{date(v.created_at)}</option>)}</select><select aria-label="Версия после" className="min-w-0 rounded border p-2 dark:bg-slate-900" value={afterId} onChange={(e) => setAfterId(e.target.value)}><option value="">Версия после</option>{versions.map((v) => <option key={v.id} value={v.id}>{v.payload.project.version ? `Версия ${v.payload.project.version} · ` : ""}{date(v.created_at)}</option>)}</select><button className="btn-secondary" disabled={!!busy} onClick={compare}>{busy === "compare" ? "Сравниваем…" : "Сравнить"}</button></div>{totals && <p className="mt-2 text-sm">Известная сумма: {totals.before.toLocaleString("ru-RU")} ₽ → {totals.after.toLocaleString("ru-RU")} ₽. Изменений: {changes.length}.</p>}{changes.map((c, i) => <p key={`${c.name}-${i}`} className="mt-1 text-sm">{c.name}: количество {c.before ?? "—"} → {c.after ?? "—"} {c.unit ?? ""}; цена {c.oldPrice ?? "не указана"} → {c.newPrice ?? "не указана"} ₽.</p>)}</div>
    {aiAvailable ? <div className="mt-4 min-w-0"><p className="text-sm font-semibold">Вопрос по проекту</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Вопрос и состав сметы отправляются внешнему провайдеру. Контакты, заказчик, объект и заметки не передаются.</p><div className="mt-2 grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><input aria-label="Вопрос по проекту" maxLength={1000} className="min-w-0 rounded border p-2 dark:bg-slate-900" value={question} onChange={(e) => setQuestion(e.target.value)} /><button className="btn-secondary" disabled={!!busy || !question.trim()} onClick={ask}>{busy === "ai" ? "Отправляем…" : "Спросить"}</button></div><p className="mt-1 text-xs text-slate-500">{question.length}/1000</p>{answer && <p className="mt-2 text-sm">{answer}</p>}</div> : <p className="mt-4 text-sm text-slate-500 dark:text-slate-400">Помощник проекта пока не включён: для него нужны подтверждённые ставки и серверная настройка.</p>}
  </section>;
}
