"use client";

import { useMemo, useRef, useState } from "react";
import ToolSectionNav from "@/components/tools/ToolSectionNav";
import { ToolMetric, ToolNotes, ToolNumberInput, ToolPresetButton } from "@/components/tools/VisualToolPrimitives";
import { useToolAnalytics } from "@/components/tools/useToolAnalytics";
import { calculateLinearCutLayout, type LinearCutPartInput } from "@/lib/tools/linear-cut-layout";

const COLORS = ["#7c3aed", "#0284c7", "#059669", "#d97706", "#e11d48", "#4f46e5", "#0f766e", "#9333ea"];
const EXAMPLES: Array<{ label: string; stock: number; kerf: number; parts: LinearCutPartInput[] }> = [
  { label: "Плинтус комнаты", stock: 2400, kerf: 2, parts: [{ id: "long", label: "Длинный участок", lengthMm: 1900, quantity: 2 }, { id: "short", label: "Короткий участок", lengthMm: 1350, quantity: 2 }, { id: "door", label: "Добор у двери", lengthMm: 420, quantity: 2 }] },
  { label: "Профиль каркаса", stock: 3000, kerf: 3, parts: [{ id: "post", label: "Стойка", lengthMm: 2600, quantity: 8 }, { id: "bridge", label: "Перемычка", lengthMm: 580, quantity: 10 }] },
  { label: "Рейки для рамок", stock: 2800, kerf: 3, parts: [{ id: "vertical", label: "Вертикаль", lengthMm: 900, quantity: 8 }, { id: "horizontal", label: "Горизонталь", lengthMm: 600, quantity: 8 }] },
];

function CutBars({ result }: { result: ReturnType<typeof calculateLinearCutLayout> }) {
  const colorByPart = new Map<string, string>(); let colorIndex = 0;
  result.stock.forEach((stock) => stock.placements.forEach((piece) => { if (!colorByPart.has(piece.partId)) { colorByPart.set(piece.partId, COLORS[colorIndex % COLORS.length]); colorIndex += 1; } }));
  return <div className="space-y-3">{result.stock.slice(0, 16).map((stock) => <div key={stock.index} className="rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="mb-2 flex flex-wrap items-center justify-between gap-2 text-xs"><strong className="text-slate-700 dark:text-slate-200">Заготовка {stock.index}</strong><span className={stock.reusable ? "font-medium text-emerald-700 dark:text-emerald-400" : "text-slate-500"}>остаток {Math.round(stock.offcutMm)} мм{stock.reusable ? " · сохранить" : ""}</span></div><svg viewBox={`0 0 ${result.input.stockLengthMm} 130`} className="h-14 w-full overflow-hidden rounded-lg bg-slate-100 dark:bg-slate-900" role="img" aria-label={`Карта раскроя заготовки ${stock.index}`}>{stock.placements.map((piece) => <g key={piece.id}>{piece.kerfBeforeMm > 0 && <rect x={piece.xMm - piece.kerfBeforeMm} width={piece.kerfBeforeMm} height="130" fill="#fff" />}<rect x={piece.xMm} width={piece.lengthMm} height="130" fill={colorByPart.get(piece.partId)} stroke="#fff" strokeWidth="3" /><text x={piece.xMm + piece.lengthMm / 2} y="49" textAnchor="middle" fill="#fff" fontSize="31" fontWeight="750">{piece.label}</text><text x={piece.xMm + piece.lengthMm / 2} y="91" textAnchor="middle" fill="#fff" fontSize="28">{piece.lengthMm} мм</text></g>)}{stock.offcutMm > 0 && <rect x={result.input.stockLengthMm - stock.offcutMm} width={stock.offcutMm} height="130" fill={stock.reusable ? "#d1fae5" : "#e2e8f0"} stroke="#64748b" strokeDasharray="8 6" strokeWidth="2" />}</svg></div>)}{result.stock.length > 16 && <p className="text-xs text-slate-500">Показаны первые 16 из {result.stock.length} заготовок. Итог учитывает все.</p>}</div>;
}

export default function LinearCutPlanner() {
  const [stockLength, setStockLength] = useState(3000); const [kerf, setKerf] = useState(3); const [reusable, setReusable] = useState(300);
  const [parts, setParts] = useState<LinearCutPartInput[]>([{ id: "a", label: "Стойка", lengthMm: 2600, quantity: 6 }, { id: "b", label: "Перемычка", lengthMm: 580, quantity: 8 }]);
  const parametersRef = useRef<HTMLDivElement>(null); const layoutRef = useRef<HTMLDivElement>(null); const resultRef = useRef<HTMLDivElement>(null);
  const { hasStarted, markStarted } = useToolAnalytics("lineynyy-raskroy", resultRef);
  const result = useMemo(() => calculateLinearCutLayout({ stockLengthMm: stockLength, sawKerfMm: kerf, reusableOffcutMm: reusable, parts }), [kerf, parts, reusable, stockLength]);
  const updatePart = (id: string, patch: Partial<LinearCutPartInput>) => { markStarted("material_size"); setParts((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item)); };
  const addPart = () => { markStarted("material_size"); setParts((items) => [...items, { id: `part-${Date.now()}`, label: `Деталь ${items.length + 1}`, lengthMm: 1000, quantity: 1 }]); };
  const applyExample = (example: (typeof EXAMPLES)[number]) => { markStarted("preset"); setStockLength(example.stock); setKerf(example.kerf); setParts(example.parts); };
  const scroll = (ref: { current: HTMLElement | null }) => ref.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  return <div className="max-w-5xl space-y-6">
    <div ref={parametersRef} className="card scroll-mt-24 space-y-5 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-900 dark:text-slate-100">Заготовка и детали</h2><p className="mt-1 text-xs text-slate-500">Подходит для любого материала, который режется по одной длине.</p></div><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-medium text-violet-700 dark:bg-violet-900/30 dark:text-violet-300">{result.partCount} деталей · {result.stockCount} заготовок</span></div>
      <div className="grid gap-4 sm:grid-cols-3"><ToolNumberInput label="Длина заготовки" value={stockLength} unit="мм" min={100} max={20000} step={100} onChange={(v) => { markStarted("material_size"); setStockLength(v); }} /><ToolNumberInput label="Ширина пропила" value={kerf} unit="мм" min={0} max={20} step={0.5} onChange={(v) => { markStarted("material_size"); setKerf(v); }} /><ToolNumberInput label="Полезный остаток от" value={reusable} unit="мм" min={0} max={20000} step={50} onChange={(v) => { markStarted("material_size"); setReusable(v); }} /></div>
      <div className="flex flex-wrap gap-2">{EXAMPLES.map((example) => <ToolPresetButton key={example.label} onClick={() => applyExample(example)}>{example.label}</ToolPresetButton>)}</div>
      <div className="border-t border-slate-100 pt-5 dark:border-slate-800"><div className="mb-3 grid grid-cols-[minmax(0,1fr)_96px_72px_36px] gap-2 px-1 text-[11px] font-medium uppercase tracking-wide text-slate-400"><span>Название</span><span>Длина, мм</span><span>Штук</span><span /></div><div className="space-y-2">{parts.map((part) => <div key={part.id} className="grid grid-cols-[minmax(0,1fr)_96px_72px_36px] gap-2"><input value={part.label} onChange={(e) => updatePart(part.id, { label: e.target.value })} className="input-field min-w-0 w-full" aria-label="Название детали" /><input type="number" inputMode="numeric" value={part.lengthMm} min={1} max={50000} onChange={(e) => updatePart(part.id, { lengthMm: Number(e.target.value) })} className="input-field min-w-0 w-full" aria-label="Длина детали" /><input type="number" inputMode="numeric" value={part.quantity} min={0} max={200} onChange={(e) => updatePart(part.id, { quantity: Number(e.target.value) })} className="input-field min-w-0 w-full" aria-label="Количество деталей" /><button type="button" onClick={() => setParts((items) => items.filter((item) => item.id !== part.id))} disabled={parts.length === 1} className="rounded-lg border border-slate-200 text-slate-400 hover:border-rose-300 hover:text-rose-600 disabled:opacity-30 dark:border-slate-700" aria-label={`Удалить ${part.label}`}>×</button></div>)}</div><button type="button" onClick={addPart} className="mt-3 w-full rounded-xl border border-dashed border-violet-300 px-4 py-2.5 text-sm font-medium text-violet-700 hover:bg-violet-50 dark:border-violet-800 dark:text-violet-300 dark:hover:bg-violet-950/20">+ Добавить деталь</button></div>
    </div>
    <ToolSectionNav visible={hasStarted} onParameters={() => scroll(parametersRef)} onLayout={() => scroll(layoutRef)} onResult={() => scroll(resultRef)} />
    <div ref={layoutRef} className="card scroll-mt-24 p-4 sm:p-6"><div className="mb-4"><h2 className="font-semibold text-slate-900 dark:text-slate-100">Карты раскроя</h2><p className="mt-1 text-xs text-slate-500">Белые линии — пропил; пунктирный хвост — остаток заготовки.</p></div>{result.stock.length > 0 ? <CutBars result={result} /> : <div className="rounded-xl bg-slate-50 p-8 text-center text-sm text-slate-500 dark:bg-slate-900">Добавьте детали, которые короче покупной заготовки.</div>}</div>
    <div ref={resultRef} className="card scroll-mt-24 p-5 sm:p-6"><div className="rounded-2xl border border-violet-200 bg-violet-50 p-4 dark:border-violet-800/60 dark:bg-violet-900/20"><p className="text-xs font-semibold uppercase tracking-wide text-violet-700 dark:text-violet-300">Купить заготовок</p><p className="mt-1 text-4xl font-bold text-slate-950 dark:text-white">{result.stockCount}</p><p className="mt-1 text-xs text-slate-500">по {result.input.stockLengthMm} мм · всего {result.purchasedLengthM} пог. м</p></div><div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-4"><ToolMetric value={`${result.exactLengthM} м`} label="Чистая длина деталей" tone="violet" /><ToolMetric value={`${result.offcutLengthM} м`} label="Суммарный остаток" /><ToolMetric value={`${result.wastePercent}%`} label="Остаток раскроя" /><ToolMetric value={result.reusableOffcuts} label="Полезных остатков" tone="emerald" /></div><ToolNotes warnings={result.errors} notes={result.notes} /></div>
  </div>;
}
