"use client";

import { useCallback, useMemo, useRef, useState } from "react";
import CompactToolWorkspaceNav from "@/components/tools/CompactToolWorkspaceNav";
import { ToolMetric, ToolNotes, ToolNumberInput, ToolPresetButton } from "@/components/tools/VisualToolPrimitives";
import { useToolAnalytics } from "@/components/tools/useToolAnalytics";
import { calculateLinearCutLayout, type LinearCutPartInput } from "@/lib/tools/linear-cut-layout";

const COLORS = ["#7c3aed", "#0284c7", "#059669", "#d97706", "#e11d48", "#4f46e5", "#0f766e", "#9333ea"];
const EXAMPLES: Array<{ label: string; stock: number; kerf: number; parts: LinearCutPartInput[] }> = [
  { label: "Плинтус комнаты", stock: 2400, kerf: 2, parts: [{ id: "long", label: "Длинный участок", lengthMm: 1900, quantity: 2 }, { id: "short", label: "Короткий участок", lengthMm: 1350, quantity: 2 }, { id: "door", label: "Добор у двери", lengthMm: 420, quantity: 2 }] },
  { label: "Профиль каркаса", stock: 3000, kerf: 3, parts: [{ id: "post", label: "Стойка", lengthMm: 2600, quantity: 8 }, { id: "bridge", label: "Перемычка", lengthMm: 580, quantity: 10 }] },
  { label: "Профильная труба", stock: 6000, kerf: 3, parts: [{ id: "frame-long", label: "Стойка рамы", lengthMm: 1900, quantity: 4 }, { id: "frame-short", label: "Поперечина", lengthMm: 900, quantity: 4 }] },
  { label: "Рейки для рамок", stock: 2800, kerf: 3, parts: [{ id: "vertical", label: "Вертикаль", lengthMm: 900, quantity: 8 }, { id: "horizontal", label: "Горизонталь", lengthMm: 600, quantity: 8 }] },
];
type LinearCutWorkspaceStage = "parameters" | "layout" | "result";
const LINEAR_CUT_WORKSPACE_STAGES = [
  { value: "parameters", shortLabel: "Параметры", label: "Заготовка и детали" },
  { value: "layout", shortLabel: "Схема", label: "Карты раскроя" },
  { value: "result", shortLabel: "Результат", label: "Итог к покупке" },
] satisfies Array<{ value: LinearCutWorkspaceStage; shortLabel: string; label: string }>;

function CutBars({ result }: { result: ReturnType<typeof calculateLinearCutLayout> }) {
  const colorByPart = new Map<string, string>(); let colorIndex = 0;
  result.stock.forEach((stock) => stock.placements.forEach((piece) => { if (!colorByPart.has(piece.partId)) { colorByPart.set(piece.partId, COLORS[colorIndex % COLORS.length]); colorIndex += 1; } }));
  return <div className="space-y-3">{result.stock.slice(0, 16).map((stock) => <div key={stock.index} className="rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="mb-2 flex flex-wrap items-center justify-between gap-2 text-xs"><strong className="text-slate-700 dark:text-slate-200">Заготовка {stock.index}</strong><span className={stock.reusable ? "font-medium text-emerald-700 dark:text-emerald-400" : "text-slate-500"}>остаток {Math.round(stock.offcutMm)} мм{stock.reusable ? " · сохранить" : ""}</span></div><svg viewBox={`0 0 ${result.input.stockLengthMm} 130`} className="h-14 w-full overflow-hidden rounded-lg bg-slate-100 dark:bg-slate-900" role="img" aria-label={`Карта раскроя заготовки ${stock.index}`}>{stock.placements.map((piece) => <g key={piece.id}>{piece.kerfBeforeMm > 0 && <rect x={piece.xMm - piece.kerfBeforeMm} width={piece.kerfBeforeMm} height="130" fill="#fff" />}<rect x={piece.xMm} width={piece.lengthMm} height="130" fill={colorByPart.get(piece.partId)} stroke="#fff" strokeWidth="3" /><text x={piece.xMm + piece.lengthMm / 2} y="49" textAnchor="middle" fill="#fff" fontSize="31" fontWeight="750">{piece.label}</text><text x={piece.xMm + piece.lengthMm / 2} y="91" textAnchor="middle" fill="#fff" fontSize="28">{piece.lengthMm} мм</text></g>)}{stock.offcutMm > 0 && <rect x={result.input.stockLengthMm - stock.offcutMm} width={stock.offcutMm} height="130" fill={stock.reusable ? "#d1fae5" : "#e2e8f0"} stroke="#64748b" strokeDasharray="8 6" strokeWidth="2" />}</svg></div>)}{result.stock.length > 16 && <p className="text-xs text-slate-500">Показаны первые 16 из {result.stock.length} заготовок. Итог учитывает все.</p>}</div>;
}

export default function LinearCutPlanner() {
  const [activeStage, setActiveStage] = useState<LinearCutWorkspaceStage>("layout");
  const [stockLength, setStockLength] = useState(3000); const [kerf, setKerf] = useState(3); const [reusable, setReusable] = useState(300);
  const [parts, setParts] = useState<LinearCutPartInput[]>([{ id: "a", label: "Стойка", lengthMm: 2600, quantity: 6 }, { id: "b", label: "Перемычка", lengthMm: 580, quantity: 8 }]);
  const workspaceTopRef = useRef<HTMLDivElement>(null); const parametersRef = useRef<HTMLDivElement>(null); const layoutRef = useRef<HTMLDivElement>(null); const resultRef = useRef<HTMLDivElement>(null);
  const { markStarted } = useToolAnalytics("lineynyy-raskroy", resultRef);
  const result = useMemo(() => calculateLinearCutLayout({ stockLengthMm: stockLength, sawKerfMm: kerf, reusableOffcutMm: reusable, parts }), [kerf, parts, reusable, stockLength]);
  const updatePart = (id: string, patch: Partial<LinearCutPartInput>) => { markStarted("material_size"); setParts((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item)); };
  const addPart = () => { markStarted("material_size"); setParts((items) => [...items, { id: `part-${Date.now()}`, label: `Деталь ${items.length + 1}`, lengthMm: 1000, quantity: 1 }]); };
  const applyExample = (example: (typeof EXAMPLES)[number]) => { markStarted("preset"); setStockLength(example.stock); setKerf(example.kerf); setParts(example.parts); };
  const changeStage = useCallback((stage: LinearCutWorkspaceStage) => {
    setActiveStage(stage);
    window.requestAnimationFrame(() => workspaceTopRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }));
  }, []);
  return <div ref={workspaceTopRef} className="max-w-5xl space-y-4 scroll-mt-24">
    <CompactToolWorkspaceNav activeStage={activeStage} ariaLabel="Этапы линейного раскроя" stages={LINEAR_CUT_WORKSPACE_STAGES} onChange={changeStage} metrics={[
      { label: "Детали", value: `${result.partCount} шт.` },
      { label: "Заготовки", value: `${result.stockCount} шт.` },
      { label: "Чистая длина", value: `${result.exactLengthM} м` },
      { label: "Купить", value: `${result.purchasedLengthM} м`, accent: true },
    ]} />

    <div ref={parametersRef} hidden={activeStage !== "parameters"} className="card scroll-mt-24 space-y-4 border-stone-200 bg-[#fffdf9] p-4 dark:border-slate-700 dark:bg-slate-900 sm:p-6"><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-violet-700 dark:text-violet-300">Шаг 1</p><h2 className="mt-1 text-xl font-bold text-stone-950 dark:text-white">Заготовка и детали</h2><p className="mt-1 text-sm text-stone-500 dark:text-slate-400">Для профиля, трубы, плинтуса и любого материала, который режется по длине.</p></div>
      <details open className="group rounded-2xl border border-stone-200 bg-white dark:border-slate-700 dark:bg-slate-950"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 [&::-webkit-details-marker]:hidden"><span><span className="block text-sm font-semibold text-stone-950 dark:text-white">Покупная заготовка</span><span className="mt-0.5 block text-xs text-stone-500 dark:text-slate-400">{stockLength.toLocaleString("ru-RU")} мм · пропил {kerf} мм · полезный остаток от {reusable} мм</span></span><span aria-hidden="true" className="text-lg text-stone-400 transition-transform group-open:rotate-45">＋</span></summary><div className="space-y-3 border-t border-stone-100 px-4 pb-4 pt-3 dark:border-slate-800"><div className="grid gap-4 sm:grid-cols-3"><ToolNumberInput label="Длина заготовки" value={stockLength} unit="мм" min={100} max={20000} step={100} onChange={(v) => { markStarted("material_size"); setStockLength(v); }} /><ToolNumberInput label="Ширина пропила" value={kerf} unit="мм" min={0} max={20} step={0.5} onChange={(v) => { markStarted("material_size"); setKerf(v); }} /><ToolNumberInput label="Полезный остаток от" value={reusable} unit="мм" min={0} max={20000} step={50} onChange={(v) => { markStarted("material_size"); setReusable(v); }} /></div><div className="flex flex-wrap gap-2">{EXAMPLES.map((example) => <ToolPresetButton key={example.label} onClick={() => applyExample(example)}>{example.label}</ToolPresetButton>)}</div></div></details>
      <details className="group rounded-2xl border border-stone-200 bg-white dark:border-slate-700 dark:bg-slate-950"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 [&::-webkit-details-marker]:hidden"><span><span className="block text-sm font-semibold text-stone-950 dark:text-white">Список деталей</span><span className="mt-0.5 block text-xs text-stone-500 dark:text-slate-400">{parts.length} типов · {result.partCount} деталей</span></span><span aria-hidden="true" className="text-lg text-stone-400 transition-transform group-open:rotate-45">＋</span></summary><div className="border-t border-stone-100 px-3 pb-4 pt-3 dark:border-slate-800 sm:px-4"><div className="mb-3 grid grid-cols-[minmax(0,1fr)_88px_64px_36px] gap-2 px-1 text-[10px] font-medium uppercase tracking-wide text-slate-400 sm:grid-cols-[minmax(0,1fr)_96px_72px_36px] sm:text-[11px]"><span>Название</span><span>Длина</span><span>Штук</span><span /></div><div className="space-y-2">{parts.map((part) => <div key={part.id} className="grid grid-cols-[minmax(0,1fr)_88px_64px_36px] gap-2 sm:grid-cols-[minmax(0,1fr)_96px_72px_36px]"><input value={part.label} onChange={(e) => updatePart(part.id, { label: e.target.value })} className="input-field min-w-0 w-full" aria-label="Название детали" /><input type="number" inputMode="numeric" value={part.lengthMm} min={1} max={50000} onChange={(e) => updatePart(part.id, { lengthMm: Number(e.target.value) })} className="input-field min-w-0 w-full" aria-label="Длина детали" /><input type="number" inputMode="numeric" value={part.quantity} min={0} max={200} onChange={(e) => updatePart(part.id, { quantity: Number(e.target.value) })} className="input-field min-w-0 w-full" aria-label="Количество деталей" /><button type="button" onClick={() => setParts((items) => items.filter((item) => item.id !== part.id))} disabled={parts.length === 1} className="rounded-lg border border-slate-200 text-slate-400 hover:border-rose-300 hover:text-rose-600 disabled:opacity-30 dark:border-slate-700" aria-label={`Удалить ${part.label}`}>×</button></div>)}</div><button type="button" onClick={addPart} className="mt-3 w-full rounded-xl border border-dashed border-violet-300 px-4 py-2.5 text-sm font-medium text-violet-700 hover:bg-violet-50 dark:border-violet-800 dark:text-violet-300 dark:hover:bg-violet-950/20">+ Добавить деталь</button></div></details>
      <button type="button" onClick={() => changeStage("layout")} className="btn-primary min-h-12 w-full justify-center text-sm sm:w-auto">Построить карты раскроя →</button>
    </div>

    <div ref={layoutRef} hidden={activeStage !== "layout"} className="card scroll-mt-24 space-y-4 border-stone-200 bg-[#fffdf9] p-4 dark:border-slate-700 dark:bg-slate-900 sm:p-6"><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-violet-700 dark:text-violet-300">Шаг 2 · живая схема</p><h2 className="mt-1 text-xl font-bold text-stone-950 dark:text-white">Карты раскроя</h2><p className="mt-1 text-sm text-stone-500 dark:text-slate-400">Белые линии — пропил · пунктирный хвост — остаток заготовки</p></div><div className="max-h-[720px] overflow-auto rounded-2xl border border-stone-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950">{result.stock.length > 0 ? <CutBars result={result} /> : <div className="rounded-xl bg-slate-50 p-8 text-center text-sm text-slate-500 dark:bg-slate-900">Добавьте детали, которые короче покупной заготовки.</div>}</div><div className="grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => changeStage("parameters")} className="min-h-12 rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-stone-700 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-200">← Изменить детали</button><button type="button" onClick={() => changeStage("result")} className="btn-primary min-h-12 w-full justify-center text-sm">Посмотреть результат →</button></div></div>

    <div ref={resultRef} hidden={activeStage !== "result"} className="card scroll-mt-24 border-stone-200 bg-[#fffdf9] p-4 dark:border-slate-700 dark:bg-slate-900 sm:p-6"><div className="rounded-2xl border border-violet-200 bg-gradient-to-br from-violet-50 to-sky-50 p-4 dark:border-violet-900/50 dark:from-violet-950/20 dark:to-sky-950/10"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-violet-800 dark:text-violet-300">Паспорт раскроя</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-stone-950 dark:text-white">Линейные заготовки</h2><p className="mt-1 text-xs text-stone-600 dark:text-slate-400">{result.partCount} деталей · заготовка {stockLength.toLocaleString("ru-RU")} мм · пропил {kerf} мм</p></div><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-semibold text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300">Обрезки учтены</span></div></div><div className="mt-4 rounded-2xl border border-violet-200 bg-violet-50 p-4 dark:border-violet-800/60 dark:bg-violet-900/20"><p className="text-xs font-semibold uppercase tracking-wide text-violet-700 dark:text-violet-300">Заготовок к покупке</p><p className="mt-1 text-4xl font-bold text-slate-950 dark:text-white">{result.stockCount}</p><p className="mt-1 text-xs text-slate-500">по {result.input.stockLengthMm} мм · всего {result.purchasedLengthM} пог. м</p></div><div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-4"><ToolMetric value={`${result.exactLengthM} м`} label="Чистая длина деталей" tone="violet" /><ToolMetric value={`${result.offcutLengthM} м`} label="Суммарный остаток" /><ToolMetric value={`${result.wastePercent}%`} label="Остаток раскроя" /><ToolMetric value={result.reusableOffcuts} label="Полезных остатков" tone="emerald" /></div><ToolNotes warnings={result.errors} notes={result.notes} /><button type="button" onClick={() => changeStage("layout")} className="mt-5 min-h-11 w-full rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-stone-600 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-300">← Вернуться к картам</button></div>
  </div>;
}
